### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by MiPnamic** [ObsComp/7dtd-Discordian-Linux#4]
on Ubuntu 20.04.1
openssl and libssl-dev already installed

The main issue here rely on the fact that newer linux uses libssl3 and the bot is still using libssl1.

I fixed manually installing
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4_amd64.deb
but this should be addressed.

Better if you upgrade to libssl3.

**Comment by ObsComp** [comment]
Discordian relies on a third party library which keeps up with that factor. I require it to be able to produce a C# based bot. Very few exist. They are superior in response times and capacity but they also break every single time Discord patches things. They have added a lot of useless junk which has broken the library I require a few times. I have put Discordian aside for now until they figure out how they want users to be named and stop breaking the API back end for bots. They have changed it four times this year alone. I also work on ServerTools, the optimizer and Discordian alone. I simply do not have time to keep up with it. It will get an update at some point but I would not rely on it as your sole Discord bot, sorry. When the game exits early access, I will consider making Discordian a core tool people will want to use with lots of features, commands and permissions. Adding any of that now is chaos due to the Discord devs changing the internal code mixed with 7 days still being in an alpha state.

If demand for Discordian was higher, I would certainly consider it. As it stands, I barely know anyone that uses it. Probably because I don't keep it up to date but again, I don't have time or patience for Discord who gives no api instructions, no information about their changes, no programming examples and then thinks its a good idea to constantly change their internal code operations and user data formations almost monthly

Most bots do not use C# and so they merely update the new data set changes. I have to wait for a third party library and then based on how they interface the new changes, I have to code for that.
________________________________
From: Marco Orlandin ***@***.***>
Sent: June 26, 2023 10:38 AM
To: ObsComp/7dtd-Discordian-Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ObsComp/7dtd-Discordian-Linux] No usable version of libssl was found (Issue #4)


on Ubuntu 20.04.1
openssl and libssl-dev already installed

The main issue here rely on the fact that newer linux uses libssl3 and the bot is still using libssl1.

I fixed manually installing
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4_amd64.deb
but this should be addressed.

Better if you upgrade to libssl3.

**Comment by MiPnamic** [comment]
Thank you so much for your feedback and for your work in any case.
